postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pig_latin
  password: igpay_atinlay

development:
  <<: *postgres
  database: pig_latin_development

test:
  <<: *postgres
  database: pig_latin_test

production:
  <<: *postgres
  database: pig_latin_production
